<?php
/**
 * Test file to verify white text CSS variables are generated correctly
 * 
 * This file demonstrates what CSS variables will be generated by the
 * portfoliocraft_inline_styles() function with the new white text colors.
 * 
 * Expected Output:
 * :root{
 *   --primary-color: var(--subtitle-text-color);
 *   --secondary-color: #010101;
 *   --third-color: #00c5fe;
 *   --body-bg-color: #fff;
 *   --white-text-color: #ffffff;
 *   --light-text-color: #f5f5f5;
 *   --off-white-color: #fafafa;
 *   --light-gray-text-color: #e0e0e0;
 *   --link-color: #1F1F1F;
 *   --link-color-hover: #F14F44;
 *   --link-color-active: #F14F44;
 *   --gradient-color-from: #6000ff;
 *   --gradient-color-to: #fe0054;
 *   --primary-font: Kanit;
 *   --secondary-font: Montserrat;
 *   --heading-font: Sora;
 * }
 * 
 * Usage Examples:
 * 
 * For white text on dark backgrounds:
 * .dark-section { color: var(--white-text-color, #ffffff); }
 * 
 * For light gray text on dark backgrounds:
 * .dark-section .subtitle { color: var(--light-text-color, #f5f5f5); }
 * 
 * For off-white text:
 * .overlay-text { color: var(--off-white-color, #fafafa); }
 * 
 * For muted text on dark backgrounds:
 * .dark-section .meta { color: var(--light-gray-text-color, #e0e0e0); }
 */

// This file is for documentation purposes only
// Do not include in production - it's just for testing and verification
?>